name: datahub
# This is the standard conda configuration file. Use this file to list
# the conda packages that you need installed in your environment.
channels:
  - conda-forge
  
dependencies:
  # Items required for basic level functionality
  - gh-scoped-creds==4.1
  - git==2.47.1
  - jupyter-archive==3.4.0
  - jupyter-offlinenotebook==0.3.1
  - jupyter-resource-usage==1.1.0  
  - jupyter-server-proxy==4.4.0
  - jupyter_server==2.15.0 
  - jupyterhub==5.2.1
  - jupyterlab==4.3.4
  - jupyterlab-git==0.50.2
  - jupyterlab_rise==0.43.1
  - jupytext==1.16.6
  - nbgitpuller==1.2.1
  - notebook==7.3.2
  - otter-grader==6.1.0
  - pip==24.3.1  
  - python==3.11.*

  # other packages
  - appmode==1.0.0
  - ipykernel = 6.29.5
  - ipywidgets==8.1.5
  - jupyterlab-geojson==3.4.0
  - jupyter-rsession-proxy==2.2.1
  - jupyter-syncthing-proxy==1.0.3
  - nbclassic==1.0.0
  - requests==2.32.3
  - syncthing==1.29.2
  - traitlets=5.14.3

  # vscode
  - jupyter-vscode-proxy==0.6
  - code-server==4.96.2

  # jupyterbook
  - mystmd==1.3.19

  # Base scientific packages that other conda packages we install depend on
  # We don't want to have conda packages depend on pip packages if possible
  - decorator=5.1.1
  - ipympl=0.9.*
  - matplotlib=3.10.*
  - networkx=3.4.2
  - nltk=3.9.1
  - numpy=2.2.*
  - pandas==2.2.3
  - scikit-learn=1.6.0
  - scipy=1.14.1
  - seaborn=0.13.2
  - spacy==3.8.2
  - statsmodels=0.14.4

  - pip:
    - git-credential-helpers==0.2
    - jupyter-shiny-proxy==1.3.0
    - nbconvert[webpdf]==7.16.5

    # ATTEMPT TO PUT NEW PACKAGES IN THE CONDA LIST ABOVE FIRST, RATHER THAN PIP
