dependencies:
- nodejs==15.*
- pip==20.2.*
- python==3.9.*

# pymc3 needs this
- mkl-service==2.4.*

# Base scientific packages that other conda packages we install depend on
# We don't want to have conda packages depend on pip packages if possible
- numpy==1.21.*
- matplotlib==3.4.*
- scipy==1.7.*
- ipympl==0.8.*
- pandas==1.3.*
- statsmodels==0.12.*
- scikit-learn==0.24.*
- seaborn==0.11.*
- bokeh==2.3.*
- decorator==5.0.*
- networkx==2.6.*
- spacy==3.1.*
- nltk==3.6.*

# data-x; DL
- tensorflow==2.6.*
- scikit-image==0.18.*

# EPS88, data100
# https://github.com/berkeley-dsep-infra/datahub/issues/1796
# https://github.com/berkeley-dsep-infra/datahub/issues/2824
- shapely==1.8.*
- cartopy==0.20.*
# data100, geog88
# https://github.com/berkeley-dsep-infra/datahub/issues/2838
- geopandas==0.10.*
- geopy==2.2.*
- pysal==2.5.*
- rtree==0.9.*
- netcdf4==1.5.*
- mplleaflet==0.0.5

# ls 88-3; neuro
- pillow==8.3.*