# https://docs.conda.io/projects/conda-build/en/latest/resources/package-spec.html#examples
# For conda, == is exact constraint, while = is fuzzy constraint.
# pip uses https://peps.python.org/pep-0440/ which does not have =.
dependencies:
- nodejs=18.*
- traitlets=5.9.*
- pip=22.2.*
- python=3.11.*
- syncthing==1.18.6
- nbclassic==1.0.0

# Matches version in images/hub/Dockerfile
- jupyterhub==5.2.1

- jupyterlab==4.3.4
- notebook==7.3.2
- ipykernel = 6.29.5
- ipywidgets==8.1.5
- nbgitpuller==1.2.1
- appmode==1.0.0
- jupyter-resource-usage==1.1.0
- jupyter-server-proxy==4.4.0
- jupyter-rsession-proxy==2.2.1
- jupyterlab-git==0.50.2

# syncthing for dropbox-like functionality
- jupyter-syncthing-proxy==1.0.3

# jupyter archival tool for easy user downloads
- jupyter-archive==3.4.0

# vscode
- jupyter-vscode-proxy==0.6
- code-server==4.96.2

# jupyterbook
- mystmd==1.3.19

# gh-scoped-creds needs a newer version of git than what jammy provides
- git==2.47.0

# pymc3 needs this
- mkl-service=2.4.*

# Base scientific packages that other conda packages we install depend on
# We don't want to have conda packages depend on pip packages if possible
- numpy=2.2.*
- matplotlib=3.10.*
- scipy=1.14.1
- ipympl=0.9.*
- pandas==2.2.3
- statsmodels=0.14.4
- scikit-learn=1.6.0
- seaborn=0.13.2
- decorator=5.1.1
- networkx=3.4.2
- spacy==3.8.2
- nltk=3.9.1

- requests==2.31.0

# [DH-384], L&S 22, Fall 2024
# Packages listed below will be used during SP 25
- typing_extensions==4.12.2
- spacy-model-en_core_web_sm=3.8.0
- spacy-model-en_core_web_md=3.8.0
# This is 3y old as of 2025-01 and cannot be installed with newer numpy
#- lemminflect=0.2.2

# ls 88-3; neuro
- pillow=11.1.0

# MUSIC 30, https://github.com/berkeley-dsep-infra/datahub/issues/5047
#- music21==8.3.0

# modules
- beautifulsoup4==4.12.3

# PS88, Fall '21 and "future iterations of the class."
# https://github.com/berkeley-dsep-infra/datahub/issues/2925
- linearmodels==6.1

# JupyterLab pypi extensions
- jupyterlab-geojson==3.4.0

# INDENG 142 Spring 2021 (future semesters as well) - https://github.com/berkeley-dsep-infra/datahub/issues/2314
- fancyimpute==0.7.0

# 2024-08 workshop, #5908
- tree==2.2.1
- ruff==0.8.5

# Stat 165/265 requires prophet, Spring, 2024
- prophet==1.1.6

# ENERES 131, Fall '24 and "Fall semesters for the foreseeable future"
# [DH-364] https://github.com/berkeley-dsep-infra/datahub/issues/6155
- openpyxl==3.1.5
# [DH-393] https://github.com/berkeley-dsep-infra/datahub/issues/6346
- pyogrio==0.10.0

# Google spreadsheets, Eric Van Dusen / Keeley Takimoto / Modules
- gspread-pandas==2.2.3
- gspread==5.12.4

# issue #929, SW 282 - fall 2019
# sknapp 2024-08-12:  keeping this package as i believe it's still useful
- pyreadstat==1.2.8

# issue 954, EPS24 - fall 2019
# sknapp 2024-08-12:  keeping this package as i believe it's still useful
- xarray==2024.11.0

# issue 1847; LS 22 spring 2021; "likely will need it yearly"
- python-graphviz==0.20.3

# [DH-243] https://github.com/berkeley-dsep-infra/datahub/issues/5571, Legal Studies 123, Spring 24; each Spring
- geopandas==1.0.1
- rtree==1.3.0

# sknapp 2023-12-15:  we will eventually move prob140 back to datahub in FA24
# https://jira-secure.berkeley.edu/browse/DH-203
- sympy==1.13.3

- pip:
  - git-credential-helpers==0.2
  - jupyter-shiny-proxy==1.1

  # Measure popularity of different packages in our hubs
  # https://discourse.jupyter.org/t/request-for-implementation-instrument-libraries-actively-used-by-users-on-a-jupyterhub/7994?u=yuvipanda
  - git+https://github.com/shaneknapp/python-popularity-contest.git@add-error-handling

  # RISE is useful for presentations - see https://github.com/berkeley-dsep-infra/datahub/issues/2527
  - RISE==5.7.1


  # Econ 148, Spring 2023 https://github.com/berkeley-dsep-infra/datahub/issues/4093
  - pycountry-convert==0.7.2
  # Options to convert notebooks to pdf; error converting to PDF https://github.com/berkeley-dsep-infra/datahub/issues/5062
  - nbconvert[webpdf]

  # eps 109; fall 2019
  # sknapp 2024-08-12:  keeping this package as i believe it's still useful
  - ffmpeg-python==0.2.0

  # issue #875, global 150Q/pacs 190 - fall 2019
  # sknapp 2024-08-12:  keeping this package as i believe it's still useful
  - wordcloud==1.9.3

  # sknapp 2023-12-15:  we will eventually move prob140 back to datahub in FA24
  # https://jira-secure.berkeley.edu/browse/DH-203
  - prob140==0.4.1.6

  # https://github.com/berkeley-dsep-infra/datahub/issues/2950
  # Needed to work with a new enough version of httplib2
  - httplib2>=0.22.0

  # Engineering 7 https://github.com/berkeley-dsep-infra/datahub/issues/5337
  - otter-grader==4.4.1
  - pydantic==1.10.8
  # pulled in by ottr, if not pinned to 1.16.2, 1.16.3 causes DH-323
  - jupytext==1.16.2

  # https://github.com/berkeley-dsep-infra/datahub/issues/5497
  - ottr-force-save-labextension==0.1.1

  # [DH-231] Installing gh-scoped-creds for https://github.com/berkeley-dsep-infra/datahub/issues/5515
  - gh-scoped-creds==4.1

  # [DH-319] https://github.com/berkeley-dsep-infra/datahub/issues/5827, ESPM 157
  - ibis-framework[pandas,duckdb]==9.2.0
 # - jupyterlab_myst==2.4.2 (Causing issues with rendering of the latex output for a CEE course)

  # [DH-384], L&S 22, Fall 2024
  # The 0.2.2 conda-forge package is 3y old as of 2025-01 and cannot be
  # installed with newer numpy.
  - lemminflect==0.2.3

  # ATTEMPT TO PUT NEW PACKAGES IN THE CONDA LIST ABOVE FIRST, RATHER THAN PIP
